// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL-FxhTVt25qpHJ_18KOph_cBGbFod5g8',
    appId: '1:539879095543:web:9b2aef0805726d2751e7f2',
    messagingSenderId: '539879095543',
    projectId: 'rental-application-app',
    authDomain: 'rental-application-app.firebaseapp.com',
    storageBucket: 'rental-application-app.firebasestorage.app',
    measurementId: 'G-KH6T6M7M6J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx5tqqI7y6_xAVnDsD7n_iNbdJCXk01t0',
    appId: '1:539879095543:android:99673178017cd0d251e7f2',
    messagingSenderId: '539879095543',
    projectId: 'rental-application-app',
    storageBucket: 'rental-application-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARonmIP7ZaYfYTor_N6f-_blTuhfuEo1k',
    appId: '1:539879095543:ios:81d9fe09b83ee6e651e7f2',
    messagingSenderId: '539879095543',
    projectId: 'rental-application-app',
    storageBucket: 'rental-application-app.firebasestorage.app',
    iosBundleId: 'com.example.rentalApplicationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARonmIP7ZaYfYTor_N6f-_blTuhfuEo1k',
    appId: '1:539879095543:ios:81d9fe09b83ee6e651e7f2',
    messagingSenderId: '539879095543',
    projectId: 'rental-application-app',
    storageBucket: 'rental-application-app.firebasestorage.app',
    iosBundleId: 'com.example.rentalApplicationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDL-FxhTVt25qpHJ_18KOph_cBGbFod5g8',
    appId: '1:539879095543:web:a1d9c202396b713851e7f2',
    messagingSenderId: '539879095543',
    projectId: 'rental-application-app',
    authDomain: 'rental-application-app.firebaseapp.com',
    storageBucket: 'rental-application-app.firebasestorage.app',
    measurementId: 'G-SF1GW909WH',
  );
}
