import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:firebase_core/firebase_core.dart';
import 'app.dart';
// import 'firebase_options.dart'; // generated by running: flutterfire configure

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp(
    // options: DefaultFirebaseOptions.currentPlatform, // uncomment after flutterfire configure
  );

  runApp(
    const ProviderScope(
      child: PropertyRentalApp(),
    ),
  );
}
